# Automatic CI validation.
pr: none
trigger:
- main
- public/*

variables:
- template: settings/common.yml

resources:
  repositories:
  - repository: build-tools
    type: git
    endpoint: Analog
    name: Analog/mixedrealitytoolkit.build
    ref: mru-ue

jobs:
- job:
  pool:
    name: $(AgentPool)
  timeoutInMinutes: 30
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    submodules: true
  - checkout: build-tools

  - template: templates/common.yml
